# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'filmsstorm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'

  target 'filmsstormTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'filmsstormUITests' do
    # Pods for testing
  end

pod 'KeychainSwift', '~> 19.0'

end
